name: UniSpace
description: UniSpace - حساب المعدل الجامعي + شات طلابي متصل
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  translator: ^1.0.4+1
  flutter:
    sdk: flutter

  image_picker: ^1.1.2
  # واجهة التطبيق
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2

  # Firebase
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.2
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.1.3

  file_selector: ^1.0.3
  firebase_storage: ^12.3.0
  path_provider: ^2.1.4

  # لتصدير PDF (اختياري)
  pdf: ^3.11.0
  printing: ^5.13.4

  # تعريب وتواريخ
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter
  google_fonts: ^6.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  open_filex: 4.7.0



dev_dependencies:

  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  hive_generator: ^2.0.1
  build_runner: ^2.4.0

flutter_icons:
  android: true
  ios: true
  web: true
  windows: true
  image_path: "assets/app_icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/brand/
    - assets/screenshots/
    - assets/templates_dz/
    - assets/fonts/

fonts:
  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
flutter_intl:
  enabled: true
